# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.DecimalField(decimal_places=1, max_digits=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField()),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Arena')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('player', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('orientation', models.CharField(max_length=255)),
                ('hit', models.CharField(max_length=255)),
                ('shot', models.CharField(max_length=255)),
                ('health', models.CharField(max_length=255)),
                ('stun', models.CharField(max_length=255)),
                ('teamchange', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackID', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalHit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalDamage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('totalHealth', models.DecimalField(decimal_places=2, max_digits=3)),
                ('team', models.CharField(max_length=255)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('member', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='memberID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.User'),
        ),
        migrations.AddField(
            model_name='arena',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility'),
        ),
    ]
