# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-20 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='id',
            field=models.DecimalField(decimal_places=1, max_digits=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='totalDamage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='totalHealth',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='totalHit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
